name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.USER }}
        DOCKER_PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        echo "Iniciando Login 1"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "FIN login"
    - name: Build Docker image
      run: |
        docker build -t angelcrisos/docker-graphql:0.0.2 . 
        docker build -t angelcrisos/docker-graphql:latest . 
    - name: Push Docker image
      run: |
        docker push angelcrisos/docker-graphql:0.0.2 
        docker push angelcrisos/docker-graphql:latest
 #   - name: Build the Docker image
 #     run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
